[platformio]
default_envs = reterminal_e1002

[env:reterminal_e1002]
platform = espressif32@6.12.0
board = seeed_xiao_esp32s3
framework = arduino
upload_speed = 115200
monitor_speed = 115200
upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 32MB
board_upload.flash_size = 32MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags =
    -D BOARD_HAS_PSRAM
    -I include
lib_deps =
    https://github.com/Seeed-Studio/Seeed_GFX.git#79afc12a29a8a689896fd78732ce11a46a8f8cab
    bblanchon/ArduinoJson@^7.4.2
